language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y beanstalkd
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install redis
  - pip install beanstalkc
  - pip install PyYAML
# command to run tests
script:
  - tests/run_all.sh
