language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y beanstalkd
  - "sh -e /etc/init.d/beanstalkd start"
# command to install dependencies
install:
  - pip install -r test${TRAVIS_PYTHON_VERSION:0:1}_reqs.txt
# command to run tests
script:
  - tests/run_all.sh
