language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
services:
  - redis-server
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install redis
# command to run tests
script:
  - tests/run_all.sh
